### ISSUE TITLE
Feature request: Support O2 login

### ISSUE THREAD

**Issue by Kumortas** [flubshi/pvr.waipu#66]
Let users with O2 login credentials also use this service.

**Comment by flubshi** [comment]
Thanks Kumortas for creating this feature request! O2 TV is already supported in the Matrix version of this plugin (starting from version 1.3.0, current: 1.4.4).

The Leia branch of pvr.waipu (current version: 0.2.2) is focused to be stable and will not get new features, only bugixes. But we have a [backported version](https://github.com/flubshi/pvr.waipu/tree/Leia-Backported) of 1.4.0 for Kodi Leia which supports O2 TV.

I decided to focus development on Matrix branch, because pvr.waipu will be an official pvr plugin starting from this version. For Leia it is not and it is hard to release a new version, because you need to compile it for every platform/architecture. If you need pvr.waipu including support for O2 TV, you might find pre-compiled releases [here](https://jenkins.kodi.tv/job/flubshi/job/pvr.waipu/job/Leia-Backported/lastSuccessfulBuild/artifact/cmake/addons/build/zips/) or in the kodinerds forum. As an alternative, you could also try to compile it yourself.

Versions of pvr.waipu that support O2 TV should have an additional setting entry _provider/anbieter_, like this:
![image](https://user-images.githubusercontent.com/4031504/80304416-ed66f780-87b5-11ea-986f-0218643e8a85.png)

**Comment by Kumortas** [comment]
Thank you for the detailed reply. I could not manage to install the backported version on my linux kodi (and found no precompiled version as well). So I will wait for the official release of matrix.

**Comment by flubshi** [comment]
For Kodi Leia on Linux, this could work for you: [pvr.waipu_1.4.0-Leia-Backported_6e7d9e3_Linux_x86_64_recompiled.zip](https://github.com/flubshi/pvr.waipu/files/4577555/pvr.waipu_1.4.0-Leia-Backported_6e7d9e3_Linux_x86_64_recompiled.zip)
